# Generated by Django 3.1.12 on 2022-07-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.TextField(max_length=200)),
                ('blog_desc', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
