# Generated by Django 3.1.12 on 2022-07-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20220717_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_published',
            field=models.DateTimeField(null=True),
        ),
    ]
