# Generated by Django 3.1.12 on 2022-07-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social',
            field=models.TextField(null=True),
        ),
    ]
